# Site settings
title: Vedant Kashyap
description: Vedant Kashyap
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vedant Kashyap
user_description: Your go to <b>DevOps</b> guy. I love automating things. I plan to become a specialist in Amazon Web Services. Always having the curiosity and enthusiasm to learn new things and implement them! These days, I'm into Data Science. I'm currently pursuing a <a href="https://www.coursera.org/specializations/data-science-python">Coursera Certification Course</a> on <b>Data Science</b> from University of Michigan.
user_title: DevOps Associate
email: vedant15188@gmail.com
instagram_username: quietisgood
github_username: vedant15188
spotify_username: vedantkashyap97
platforms: AWS, Microsoft Azure, NGINX, IIS, Windows Server
code: Python, Javascript, C++, Powershell, Bash
tools: Git, Docker, Kubernetes, Ansible, Jenkins

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
